---
version: 2.1

executorType: machine

orbs:
  docker: circleci/docker@1.0.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose build
      - run: docker-compose run --rm nvim nvim -E -c "checkhealth" -c "q" --

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
